# Generated by Django 5.2.1 on 2025-05-28 12:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('project', 'Project Proposal'), ('collaboration', 'Collaboration'), ('job', 'Job Opportunity')], default='general', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferred_contact', models.CharField(choices=[('email1', 'Business Email'), ('email2', 'Personal Email')], default='email1', max_length=50)),
            ],
        ),
    ]
