# Generated by Django 5.1.1 on 2025-09-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='pricing_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Basic - ₹5000'), ('professional', 'Professional - ₹8000'), ('custom', 'Custom - ₹10000+')], max_length=20, null=True),
        ),
    ]
