# Generated by Django 5.1.1 on 2025-09-02 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage_pricing_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('topic', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='pricing_plan',
            field=models.CharField(blank=True, choices=[('basic', 'Basic - ₹5000'), ('professional', 'Professional - ₹8000'), ('custom', 'Custom - 9500-11000')], max_length=20, null=True),
        ),
    ]
