# Generated by Django 5.1.1 on 2025-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_meeting_alter_contactmessage_pricing_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
