# Generated by Django 5.1.1 on 2025-09-10 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_meeting_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='department',
            field=models.CharField(blank=True, choices=[('web', 'Web Development'), ('data', 'Data Analytics'), ('mobile', 'Mobile App Development'), ('social', 'Social Media')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='team_member',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.teammember'),
        ),
    ]
