# Generated by Django 5.1.1 on 2025-09-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage_department_contactmessage_team_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fallback_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('UI/UX Design', 'UI/UX Design'), ('Branding', 'Branding')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.JSONField(default=list),
        ),
    ]
