# Generated by Django 5.2.3 on 2025-11-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_email_to_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='location',
            field=models.CharField(blank=True, help_text='City/Location for this team member (e.g., Coimbatore, TN, India)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number for contact (e.g., +91 98434 64180)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from name)', null=True, unique=True),
        ),
    ]
