# Generated by Django 5.2.3 on 2025-11-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_teammember_location_teammember_phone_teammember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fallback_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
