# Generated by Django 5.2.3 on 2025-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_fallback_image_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Email of the admin who manages this profile', max_length=254, null=True, unique=True),
        ),
    ]
