# Generated by Django 5.2.3 on 2025-11-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teammember_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='google_meet_url',
            field=models.URLField(blank=True, help_text='Google Meet link for this meeting', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - Awaiting Confirmation'), ('confirmed', 'Confirmed - Meet Link Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
