# Generated by Django 5.2.3 on 2025-12-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_project_image_alter_project_fallback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fallback_image',
            field=models.ImageField(blank=True, help_text='Fallback image for project card preview', null=True, upload_to='projects/project_fallback_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project image for modal/detail view', null=True, upload_to='projects/project_images/'),
        ),
    ]
