# Generated by Django 5.2.3 on 2026-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_project_fallback_image_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fallback_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
