# Generated by Django 5.2.3 on 2026-01-22 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_project_fallback_image_alter_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
